version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    groups:
      github-actions:
        patterns: ["*"]
  - package-ecosystem: uv
    directory: /backend
    schedule:
      interval: monthly
    groups:
      uv:
        patterns: ["*"]
  - package-ecosystem: npm
    directory: /frontend
    schedule:
      interval: monthly
    groups:
      npm:
        patterns: ["*"]
